// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5juU7nfCcsjkwxXrHng0x8aWZrg5WGe0',
    appId: '1:1060712912677:web:4aa8dd0eb91c7502c66ccc',
    messagingSenderId: '1060712912677',
    projectId: 'chat-app-7bd24',
    authDomain: 'chat-app-7bd24.firebaseapp.com',
    storageBucket: 'chat-app-7bd24.appspot.com',
    measurementId: 'G-1DGFG0WE2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHA9L_WIqHbEEYwiRgkyqdVadex5eTMyM',
    appId: '1:1060712912677:android:78e37827f600579ec66ccc',
    messagingSenderId: '1060712912677',
    projectId: 'chat-app-7bd24',
    storageBucket: 'chat-app-7bd24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAmEzOzjWVIDZTVY3Nl68fxbE_kHzqcfQ',
    appId: '1:1060712912677:ios:cda0058975ed4790c66ccc',
    messagingSenderId: '1060712912677',
    projectId: 'chat-app-7bd24',
    storageBucket: 'chat-app-7bd24.appspot.com',
    iosClientId: '1060712912677-6sf4o1s0lnf44ermgc364v6pal0phd86.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAmEzOzjWVIDZTVY3Nl68fxbE_kHzqcfQ',
    appId: '1:1060712912677:ios:62733219518f4461c66ccc',
    messagingSenderId: '1060712912677',
    projectId: 'chat-app-7bd24',
    storageBucket: 'chat-app-7bd24.appspot.com',
    iosClientId: '1060712912677-494ikg7ff6dpq9eugnvmtp99mtu34fcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
